@AccessControl.authorizationCheck: #NOT_ALLOWED
@EndUserText.label: 'Interface view for GST ITC Reco'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
@Metadata.allowExtensions: true
define root view entity ZI_GST_ITC_RECO
  as select from zgstr2_reco_st
{
  key inum                   as Inum,
  key idt                    as Idt,
  key pr_inum                as PrInum,
  key pr_idt                 as PrIdt,
  key supplier_gstin         as SupplierGstin,
  key accountingdocument     as Accountingdocument,
      autorecoid             as Autorecoid,
      val                    as Val,
      nt_num                 as NtNum,
      nt_dt                  as NtDt,
      inv_typ                as InvTyp,
      pos                    as Pos,
      rchrg                  as Rchrg,
      imonth                 as Imonth,
      supplier_name          as SupplierName,
      supplier_gstin_status  as SupplierGstinStatus,
      supplier_return_type   as SupplierReturnType,
      contact_name           as ContactName,
      buyer_gstin            as BuyerGstin,
      cfs                    as Cfs,
      invoice_type           as InvoiceType,
      gstr1_filling_date     as Gstr1FillingDate,
      ttxval                 as Ttxval,
      net_amount             as NetAmount,
      itc_alg                as ItcAlg,
      transaction_number     as TransactionNumber,
      referencedocumentmiro  as Referencedocumentmiro,
      referred_invoice_date  as ReferredInvoiceDate,
      erp_document_date      as ErpDocumentDate,
      total_igst             as TotalIgst,
      total_cgst             as TotalCgst,
      total_sgst             as TotalSgst,
      total_cess             as TotalCess,
      fiscalyear             as Fiscalyear,
      status                 as Status,
      reco_action            as RecoAction,
      action_date            as ActionDate,
      reten_post             as RetenPost,
      reten_post_doc         as RetenPostDoc,
      reverse_ret            as ReverseRet,
      gstr3b_filling_status  as Gstr3bFillingStatus,
      reason                 as Reason,
      pr_supplier_name       as PrSupplierName,
      pr_buyer_gstin         as PrBuyerGstin,
      pr_gl_code             as PrGlCode,
      pr_supplier_gstin      as PrSupplierGstin,
      pr_invoice_type        as PrInvoiceType,
      pr_net_amount          as PrNetAmount,
      pr_val                 as PrVal,
      pr_nt_num              as PrNtNum,
      pr_nt_dt               as PrNtDt,
      pr_ntty                as PrNtty,
      pr_location            as PrLocation,
      pr_total_igst          as PrTotalIgst,
      pr_total_cgst          as PrTotalCgst,
      pr_total_sgst          as PrTotalSgst,
      pr_total_cess          as PrTotalCess,
      pr_org_inum            as PrOrgInum,
      pr_org_idt             as PrOrgIdt,
      pr_itc_alg             as PrItcAlg,
      pr_gstr2_return_period as PrGstr2ReturnPeriod,
      pr_erp_document_number as PrErpDocumentNumber,
      pr_erp_document_date   as PrErpDocumentDate,
      pr_fiscalyear          as PrFiscalyear,
      pr_imonth              as PrImonth,
      pr_pos                 as PrPos,
      pr_rchrg               as PrRchrg,
      pr_ttxval              as PrTtxval
}
