CLASS zbp_i_jentry_rv DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_jentry_rv.
  PUBLIC SECTION.
    CLASS-DATA : cv_avvtdoc TYPE RESPONSE FOR MAPPED i_journalentrytp.

ENDCLASS.



CLASS ZBP_I_JENTRY_RV IMPLEMENTATION.
ENDCLASS.
