@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Product Master Root Entity'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
define root view entity ZproductMasterRV 
as select from I_Product as Pro
association [1..1] to I_ProductPlantSupplyPlanning as _ProductPlantSupplyPlanning on $projection.Product = _ProductPlantSupplyPlanning.Product
{
key Pro.Product,

Pro.ProductExternalID,
Pro.ProductOID,
Pro.ProductType,
Pro.CreationDate,
Pro.CreationTime,
Pro.CreationDateTime,
Pro.CreatedByUser,
Pro.LastChangeDate,
Pro.LastChangedByUser,
Pro.IsMarkedForDeletion,
Pro.CrossPlantStatus,
Pro.CrossPlantStatusValidityDate,
Pro.ProductOldID,
@Semantics.quantity.unitOfMeasure: 'WeightUnit'
Pro.GrossWeight,
Pro.PurchaseOrderQuantityUnit,
Pro.SourceOfSupply,
Pro.WeightUnit,
Pro.CountryOfOrigin,
Pro.CompetitorID,
Pro.ProductGroup,
Pro.BaseUnit,
Pro.ItemCategoryGroup,
@Semantics.quantity.unitOfMeasure: 'WeightUnit'
Pro.NetWeight,
Pro.ProductHierarchy,
Pro.Division,
Pro.VarblPurOrdUnitIsActive,
Pro.VolumeUnit,
@Semantics.quantity.unitOfMeasure: 'VolumeUnit'
Pro.MaterialVolume,
Pro.SalesStatus,
Pro.TransportationGroup,
Pro.SalesStatusValidityDate,
Pro.AuthorizationGroup,
Pro.ANPCode,
Pro.ProductCategory,
Pro.Brand,
Pro.ProcurementRule,
Pro.ValidityStartDate,
Pro.LowLevelCode,
Pro.ProdNoInGenProdInPrepackProd,
Pro.SerialIdentifierAssgmtProfile,
Pro.SizeOrDimensionText,
Pro.IndustryStandardName,
Pro.ProductStandardID,
Pro.InternationalArticleNumberCat,
Pro.ProductIsConfigurable,
Pro.IsBatchManagementRequired,
Pro.HasEmptiesBOM,
Pro.ExternalProductGroup,
Pro.CrossPlantConfigurableProduct,
Pro.SerialNoExplicitnessLevel,
Pro.ProductManufacturerNumber,
Pro.ManufacturerNumber,
Pro.ManufacturerPartProfile,
Pro.QltyMgmtInProcmtIsActive,
Pro.IsApprovedBatchRecordReqd,
Pro.HandlingIndicator,
Pro.WarehouseProductGroup,
Pro.WarehouseStorageCondition,
Pro.StandardHandlingUnitType,
Pro.SerialNumberProfile,
Pro.AdjustmentProfile,
Pro.PreferredUnitOfMeasure,
Pro.IsPilferable,
Pro.IsRelevantForHzdsSubstances,
@Semantics.quantity.unitOfMeasure : 'TimeUnitForQuarantinePeriod'
Pro.QuarantinePeriod,
Pro.TimeUnitForQuarantinePeriod,
Pro.QualityInspectionGroup,
Pro.HandlingUnitType,
Pro.HasVariableTareWeight,
@Semantics.quantity.unitOfMeasure: 'UnitForMaxPackagingDimensions'
Pro.MaximumPackagingLength,
@Semantics.quantity.unitOfMeasure: 'UnitForMaxPackagingDimensions'
Pro.MaximumPackagingWidth,
@Semantics.quantity.unitOfMeasure: 'UnitForMaxPackagingDimensions'
Pro.MaximumPackagingHeight,
Pro.MaximumCapacity,
Pro.OvercapacityTolerance,
Pro.UnitForMaxPackagingDimensions,
 @Semantics.quantity.unitOfMeasure: 'ProductMeasurementUnit'
Pro.BaseUnitSpecificProductLength,
 @Semantics.quantity.unitOfMeasure: 'ProductMeasurementUnit'
Pro.BaseUnitSpecificProductWidth,
 @Semantics.quantity.unitOfMeasure: 'ProductMeasurementUnit'
Pro.BaseUnitSpecificProductHeight,
Pro.ProductMeasurementUnit,
Pro.ProductValidStartDate,
Pro.ArticleCategory,
Pro.ContentUnit,
@Semantics.quantity.unitOfMeasure: 'ContentUnit'
Pro.NetContent,
Pro.ComparisonPriceQuantity,
@Semantics.quantity.unitOfMeasure: 'ContentUnit'
Pro.GrossContent,
Pro.ProductValidEndDate,
Pro.AssortmentListType,
Pro.HasTextilePartsWthAnimalOrigin,
Pro.ProductSeasonUsageCategory,
Pro.IndustrySector,
Pro.ChangeNumber,
Pro.MaterialRevisionLevel,
Pro.IsActiveEntity,
Pro.LastChangeDateTime,
Pro.LastChangeTime,
Pro.DangerousGoodsIndProfile,
Pro.ProductUUID,
Pro.ProdSupChnMgmtUUID22,
Pro.ProductDocumentChangeNumber,
Pro.ProductDocumentPageCount,
Pro.ProductDocumentPageNumber,
Pro.OwnInventoryManagedProduct,
Pro.DocumentIsCreatedByCAD,
Pro.ProductionOrInspectionMemoTxt,
Pro.ProductionMemoPageFormat,
Pro.GlobalTradeItemNumberVariant,
Pro.ProductIsHighlyViscous,
Pro.TransportIsInBulk,
Pro.ProdAllocDetnProcedure,
Pro.ProdEffctyParamValsAreAssigned,
Pro.ProdIsEnvironmentallyRelevant,
Pro.LaboratoryOrDesignOffice,
Pro.PackagingMaterialGroup,
Pro.ProductIsLocked,
Pro.DiscountInKindEligibility,
Pro.SmartFormName,
Pro.PackingReferenceProduct,
Pro.BasicMaterial,
Pro.ProductDocumentNumber,
Pro.ProductDocumentVersion,
Pro.ProductDocumentType,
Pro.ProductDocumentPageFormat,
Pro.ProductConfiguration,
Pro.SegmentationStrategy,
Pro.SegmentationIsRelevant,
Pro.ProductCompositionIsRelevant,
Pro.IsChemicalComplianceRelevant,
Pro.ManufacturerBookPartNumber,
Pro.LogisticalProductCategory,
Pro.SalesProduct,
Pro.ProdCharc1InternalNumber,
Pro.ProdCharc2InternalNumber,
Pro.ProdCharc3InternalNumber,
Pro.ProductCharacteristic1,
Pro.ProductCharacteristic2,
Pro.ProductCharacteristic3,
Pro.MaintenanceStatus,
Pro.FashionProdInformationField1,
Pro.FashionProdInformationField2,
Pro.FashionProdInformationField3,
@Semantics.amount.currencyCode: 'YY1_DPCOMRP_PRDC'
Pro.YY1_DPCOMRP_PRD,
Pro.YY1_DPCOMRP_PRDC,
Pro.YY1_HighRiskMedication_PRD,
Pro.YY1_Generic_Name_PRD,
Pro.YY1_VEDAnalysis_PRD,
Pro.YY1_ScheduleCategory_PRD,
Pro.YY1_Packing_PRD,
Pro.YY1_LookAlikeLA_PRD,
Pro.YY1_TPAPayable_PRD,
Pro.YY1_PayableByHospital_PRD,
Pro.YY1_PharmaMaterialSubC_PRD,
Pro.YY1_StoragePolicy_PRD,
Pro.YY1_PharmaMaterialCate_PRD,
Pro.YY1_SoundAlikeSA_PRD,
Pro.YY1_GenericName_PRD,
Pro.YY1_NotPayableToGov_PRD,
Pro.YY1_NONPayableToECHSCG_PRD,
Pro.YY1_ServiceCharge_PRD,
_ProductPlantSupplyPlanning
}
